# These options configure both how libmementos is built and how
# the target application that wants to link libmementos is built.
# The values here are defaults. The options are meant to be
# overriden from the top-level makefile in the target app.

# The mode selects which points in the program are instrumented with checkpoints
# Available modes:
#   latch: loop boundaries
#   return: function exits
#   manual: checkpoints specified explicitly using a macro
#   oracle: no instrumentation
MEMENTOS_MODE ?= latch

# Throttle checkpoints to at most the frequency of a timer tick
MEMENTOS_TIMER ?= 1

# Ignore globals by default until Mementos is fixed to handle them correctly.
# Currently, it blindly restores globals to .data, despite them being in .bss.
MEMENTOS_IGNORE_GLOBALS ?= 1

# Mementos is not safe for non-idempotant code that manipulates NV state
# This flag is provided for convenience for applications that want
# to have a broken (unsafe) mode for evaluation purposes.
MEMENTOS_NONVOLATILE ?= 0

# Type of non-volatile memory on the target device: flash or fram
MEMENTOS_NVMEM_TYPE ?= fram
